# Generated by Django 6.0.3 on 2026-04-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0002_alter_offerdetail_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
